# Use https://travis-ci.org/ for automatic testing

# This is a java project
language: java

script: mvn compile test -U

jdk: [oraclejdk8]

# if one build failed, exit testing
matrix:
  fast_finish: true
  
